---
- name: Create teleport service (systemd).
  template:
    src: "teleport.service.j2"
    dest: "/etc/systemd/system/teleport.service"
    owner: "root"
    group: "root"
    mode: 0644
  register: service_installed
  notify: restart teleport
  when: teleport_enabled

- name: Create teleport PROD service (systemd).
  template:
    src: "teleport_prod.service.j2"
    dest: "/etc/systemd/system/teleport_prod.service"
    owner: "root"
    group: "root"
    mode: 0644
  register: service_prod_installed
  notify: restart teleport_prod
  when: teleport_prod_enabled

- name: Create teleport APPs service (systemd).
  template:
    src: "teleport_apps.service.j2"
    dest: "/etc/systemd/system/teleport_apps.service"
    owner: "root"
    group: "root"
    mode: 0644
  register: service_apps_installed
  notify: restart teleport_apps
  when: teleport_configuration_applications is defined
