---

- name: Check if teleport is installed.
  command: "/usr/local/bin/teleport version"
  changed_when: false
  register: teleport_version_check
  failed_when: false
  #stat:
  #  path: /usr/local/bin/teleport
  #register: teleport_bin

- name: Unarchive teleport.
  unarchive:
    src: "https://get.gravitational.com/teleport-v{{ teleport_version }}-linux-amd64-bin.tar.gz"
    dest: /tmp
    remote_src: yes
  when: "teleport_version_check.rc >= 1 or (teleport_version not in teleport_version_check.stdout)"

- name: Install teleport.
  command: >
    ./install
    chdir=/tmp/teleport
  become: yes
  when: "teleport_version_check.rc >= 1 or (teleport_version not in teleport_version_check.stdout)"

- name: Create teleport config.
  template:
    src: "teleport.yaml.j2"
    dest: "{{ teleport_config_path }}"
    owner: "root"
    group: "root"
    mode: 0600
  notify: restart teleport

- include_tasks: configure-Systemd.yml
  when: ansible_service_mgr == 'systemd'

- include_tasks: configure-Upstart.yml
  when: ansible_service_mgr == 'upstart'

- include_tasks: configure-Sysvinit.yml
  when: ansible_service_mgr == 'sysvinit'

- name: Ensure teleport has selected state and enabled on boot.
  service:
    name: 'teleport'
    #state: 'reloaded'
    state: 'restarted'
    enabled: yes
  changed_when: false
